// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPitchAndYawRequest {
    /// Pitch angle in degrees (negative points down)
    #[prost(float, tag = "1")]
    pub pitch_deg: f32,
    /// Yaw angle in degrees (positive is clock-wise, range: -180 to 180 or 0 to 360)
    #[prost(float, tag = "2")]
    pub yaw_deg: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPitchAndYawResponse {
    #[prost(message, optional, tag = "1")]
    pub gimbal_result: ::core::option::Option<GimbalResult>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPitchRateAndYawRateRequest {
    /// Angular rate around pitch axis in degrees/second (negative downward)
    #[prost(float, tag = "1")]
    pub pitch_rate_deg_s: f32,
    /// Angular rate around yaw axis in degrees/second (positive is clock-wise)
    #[prost(float, tag = "2")]
    pub yaw_rate_deg_s: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPitchRateAndYawRateResponse {
    #[prost(message, optional, tag = "1")]
    pub gimbal_result: ::core::option::Option<GimbalResult>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetModeRequest {
    /// The mode to be set.
    #[prost(enumeration = "GimbalMode", tag = "1")]
    pub gimbal_mode: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetModeResponse {
    #[prost(message, optional, tag = "1")]
    pub gimbal_result: ::core::option::Option<GimbalResult>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetRoiLocationRequest {
    /// Latitude in degrees
    #[prost(double, tag = "1")]
    pub latitude_deg: f64,
    /// Longitude in degrees
    #[prost(double, tag = "2")]
    pub longitude_deg: f64,
    /// Altitude in metres (AMSL)
    #[prost(float, tag = "3")]
    pub altitude_m: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetRoiLocationResponse {
    #[prost(message, optional, tag = "1")]
    pub gimbal_result: ::core::option::Option<GimbalResult>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TakeControlRequest {
    /// Control mode (primary or secondary)
    #[prost(enumeration = "ControlMode", tag = "1")]
    pub control_mode: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TakeControlResponse {
    #[prost(message, optional, tag = "1")]
    pub gimbal_result: ::core::option::Option<GimbalResult>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReleaseControlRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReleaseControlResponse {
    #[prost(message, optional, tag = "1")]
    pub gimbal_result: ::core::option::Option<GimbalResult>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeControlRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlResponse {
    /// Control status
    #[prost(message, optional, tag = "1")]
    pub control_status: ::core::option::Option<ControlStatus>,
}
/// Control status
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlStatus {
    /// Control mode (none, primary or secondary)
    #[prost(enumeration = "ControlMode", tag = "1")]
    pub control_mode: i32,
    /// Sysid of the component that has primary control over the gimbal (0 if no one is in control)
    #[prost(int32, tag = "2")]
    pub sysid_primary_control: i32,
    /// Compid of the component that has primary control over the gimbal (0 if no one is in control)
    #[prost(int32, tag = "3")]
    pub compid_primary_control: i32,
    /// Sysid of the component that has secondary control over the gimbal (0 if no one is in control)
    #[prost(int32, tag = "4")]
    pub sysid_secondary_control: i32,
    /// Compid of the component that has secondary control over the gimbal (0 if no one is in control)
    #[prost(int32, tag = "5")]
    pub compid_secondary_control: i32,
}
/// Result type.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GimbalResult {
    /// Result enum value
    #[prost(enumeration = "gimbal_result::Result", tag = "1")]
    pub result: i32,
    /// Human-readable English string describing the result
    #[prost(string, tag = "2")]
    pub result_str: ::prost::alloc::string::String,
}
/// Nested message and enum types in `GimbalResult`.
pub mod gimbal_result {
    /// Possible results returned for gimbal commands.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Result {
        /// Unknown result
        Unknown = 0,
        /// Command was accepted
        Success = 1,
        /// Error occurred sending the command
        Error = 2,
        /// Command timed out
        Timeout = 3,
        /// Functionality not supported
        Unsupported = 4,
        /// No system connected
        NoSystem = 5,
    }
    impl Result {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Result::Unknown => "RESULT_UNKNOWN",
                Result::Success => "RESULT_SUCCESS",
                Result::Error => "RESULT_ERROR",
                Result::Timeout => "RESULT_TIMEOUT",
                Result::Unsupported => "RESULT_UNSUPPORTED",
                Result::NoSystem => "RESULT_NO_SYSTEM",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "RESULT_UNKNOWN" => Some(Self::Unknown),
                "RESULT_SUCCESS" => Some(Self::Success),
                "RESULT_ERROR" => Some(Self::Error),
                "RESULT_TIMEOUT" => Some(Self::Timeout),
                "RESULT_UNSUPPORTED" => Some(Self::Unsupported),
                "RESULT_NO_SYSTEM" => Some(Self::NoSystem),
                _ => None,
            }
        }
    }
}
/// Gimbal mode type.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GimbalMode {
    /// Yaw follow will point the gimbal to the vehicle heading
    YawFollow = 0,
    /// Yaw lock will fix the gimbal poiting to an absolute direction
    YawLock = 1,
}
impl GimbalMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            GimbalMode::YawFollow => "GIMBAL_MODE_YAW_FOLLOW",
            GimbalMode::YawLock => "GIMBAL_MODE_YAW_LOCK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GIMBAL_MODE_YAW_FOLLOW" => Some(Self::YawFollow),
            "GIMBAL_MODE_YAW_LOCK" => Some(Self::YawLock),
            _ => None,
        }
    }
}
/// Control mode
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ControlMode {
    /// Indicates that the component does not have control over the gimbal
    None = 0,
    /// To take primary control over the gimbal
    Primary = 1,
    /// To take secondary control over the gimbal
    Secondary = 2,
}
impl ControlMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ControlMode::None => "CONTROL_MODE_NONE",
            ControlMode::Primary => "CONTROL_MODE_PRIMARY",
            ControlMode::Secondary => "CONTROL_MODE_SECONDARY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CONTROL_MODE_NONE" => Some(Self::None),
            "CONTROL_MODE_PRIMARY" => Some(Self::Primary),
            "CONTROL_MODE_SECONDARY" => Some(Self::Secondary),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod gimbal_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Provide control over a gimbal.
    #[derive(Debug, Clone)]
    pub struct GimbalServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl GimbalServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> GimbalServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> GimbalServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            GimbalServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        ///
        ///
        /// Set gimbal pitch and yaw angles.
        ///
        /// This sets the desired pitch and yaw angles of a gimbal.
        /// Will return when the command is accepted, however, it might
        /// take the gimbal longer to actually be set to the new angles.
        pub async fn set_pitch_and_yaw(
            &mut self,
            request: impl tonic::IntoRequest<super::SetPitchAndYawRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPitchAndYawResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mavsdk.rpc.gimbal.GimbalService/SetPitchAndYaw",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("mavsdk.rpc.gimbal.GimbalService", "SetPitchAndYaw"),
                );
            self.inner.unary(req, path, codec).await
        }
        ///
        ///
        /// Set gimbal angular rates around pitch and yaw axes.
        ///
        /// This sets the desired angular rates around pitch and yaw axes of a gimbal.
        /// Will return when the command is accepted, however, it might
        /// take the gimbal longer to actually reach the angular rate.
        pub async fn set_pitch_rate_and_yaw_rate(
            &mut self,
            request: impl tonic::IntoRequest<super::SetPitchRateAndYawRateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPitchRateAndYawRateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mavsdk.rpc.gimbal.GimbalService/SetPitchRateAndYawRate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "mavsdk.rpc.gimbal.GimbalService",
                        "SetPitchRateAndYawRate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        ///
        /// Set gimbal mode.
        ///
        /// This sets the desired yaw mode of a gimbal.
        /// Will return when the command is accepted. However, it might
        /// take the gimbal longer to actually be set to the new angles.
        pub async fn set_mode(
            &mut self,
            request: impl tonic::IntoRequest<super::SetModeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetModeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mavsdk.rpc.gimbal.GimbalService/SetMode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mavsdk.rpc.gimbal.GimbalService", "SetMode"));
            self.inner.unary(req, path, codec).await
        }
        ///
        /// Set gimbal region of interest (ROI).
        ///
        /// This sets a region of interest that the gimbal will point to.
        /// The gimbal will continue to point to the specified region until it
        /// receives a new command.
        /// The function will return when the command is accepted, however, it might
        /// take the gimbal longer to actually rotate to the ROI.
        pub async fn set_roi_location(
            &mut self,
            request: impl tonic::IntoRequest<super::SetRoiLocationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetRoiLocationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mavsdk.rpc.gimbal.GimbalService/SetRoiLocation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("mavsdk.rpc.gimbal.GimbalService", "SetRoiLocation"),
                );
            self.inner.unary(req, path, codec).await
        }
        ///
        /// Take control.
        ///
        /// There can be only two components in control of a gimbal at any given time.
        /// One with "primary" control, and one with "secondary" control. The way the
        /// secondary control is implemented is not specified and hence depends on the
        /// vehicle.
        ///
        /// Components are expected to be cooperative, which means that they can
        /// override each other and should therefore do it carefully.
        pub async fn take_control(
            &mut self,
            request: impl tonic::IntoRequest<super::TakeControlRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TakeControlResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mavsdk.rpc.gimbal.GimbalService/TakeControl",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("mavsdk.rpc.gimbal.GimbalService", "TakeControl"),
                );
            self.inner.unary(req, path, codec).await
        }
        ///
        /// Release control.
        ///
        /// Release control, such that other components can control the gimbal.
        pub async fn release_control(
            &mut self,
            request: impl tonic::IntoRequest<super::ReleaseControlRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReleaseControlResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mavsdk.rpc.gimbal.GimbalService/ReleaseControl",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("mavsdk.rpc.gimbal.GimbalService", "ReleaseControl"),
                );
            self.inner.unary(req, path, codec).await
        }
        ///
        /// Subscribe to control status updates.
        ///
        /// This allows a component to know if it has primary, secondary or
        /// no control over the gimbal. Also, it gives the system and component ids
        /// of the other components in control (if any).
        pub async fn subscribe_control(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeControlRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ControlResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mavsdk.rpc.gimbal.GimbalService/SubscribeControl",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "mavsdk.rpc.gimbal.GimbalService",
                        "SubscribeControl",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
